name: Terraform Validation
on:
  push:
  # Scheduled runs ensure we are alerted to incompatibilities in new releases
  # of Terraform.
  schedule:
    - cron: '0 10 * * 3'

permissions: read-all

jobs:

  terraform:
    name: Validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "latest"
          - "1.4.2"

    steps:

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '${{ matrix.version }}'

      - uses: actions/checkout@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
